INSERT INTO Subjects VALUES (N'Иностранный язык', 108)
INSERT INTO Subjects VALUES (N'Математика', 144)
INSERT INTO Subjects VALUES (N'Инженерная графика', 108)
INSERT INTO Subjects VALUES (N'Основы деловой коммуникации', 72)
INSERT INTO Subjects VALUES (N'Информатика', 108)
INSERT INTO Subjects VALUES (N'Физика', 108)
INSERT INTO Subjects VALUES (N'Физкультура', 72)
INSERT INTO Subjects VALUES (N'История', 144)
INSERT INTO Subjects VALUES (N'Программирование на ЯВУ', 180)